apiVersion: v1
kind: Pod
metadata:
  name: nginxpod-pv
  labels:
    app-pv: nginx
spec:
  containers:
  - image: nginx
    name: my-nginx
    ports:
      - containerPort: 80
    volumeMounts:
     - mountPath: "/usr/share/nginx/html"
       name: nginx-storage
  volumes:
   - name: nginx-storage
     persistentVolumeClaim:
       claimName: pvc-nginx
